<a href="https://colab.research.google.com/github/babaroscopy/colab/blob/main/Tasawar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, LSTM, BatchNormalization
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [39]:
df = pd.read_csv("google.csv", header=None)
#X = np.array(df.iloc[:, df.columns != 16])
#Y = np.array(df.iloc[:, df.columns == 16])
X = df.iloc[:,0:16].values
y = df.iloc[:,16].values

In [40]:
print(X[0:5])
print(y[0:5])

[[3.418309e+06 1.000000e+00 1.568000e-03 6.787000e-02 7.556000e-02
  3.195000e-04 7.000000e-04 6.787000e-02 1.879000e-04 3.302000e-02
  9.289000e-04 2.100000e+00 5.791000e-03 0.000000e+00 1.000000e+00
  0.000000e+00]
 [3.418314e+06 0.000000e+00 3.071000e-04 8.044000e-02 9.521000e-02
  2.823000e-04 6.704000e-04 8.044000e-02 1.841000e-04 2.377000e-02
  7.858000e-04 5.588000e+00 2.080000e-02 0.000000e+00 1.000000e+00
  0.000000e+00]
 [3.418314e+06 1.000000e+00 3.004000e-04 8.044000e-02 9.521000e-02
  5.369000e-04 8.698000e-04 8.044000e-02 1.831000e-04 7.919000e-03
  2.285000e-03 5.198000e+00 2.038000e-02 0.000000e+00 1.000000e+00
  0.000000e+00]
 [3.418319e+06 0.000000e+00 4.606000e-04 7.715000e-02 8.740000e-02
  6.247000e-04 8.516000e-04 7.715000e-02 2.041000e-04 5.112000e-03
  2.146000e-04 2.937000e+00 9.449000e-03 0.000000e+00 1.000000e+00
  0.000000e+00]
 [3.418319e+06 1.000000e+00 5.188000e-04 7.678000e-02 8.740000e-02
  3.376000e-04 7.210000e-04 7.678000e-02 2.041000e-04 1.508000e-0

In [41]:
print(X.shape)
print(y.shape)

(5000, 16)
(5000,)


In [42]:
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [43]:
print(y1)

[0 0 0 ... 0 0 0]


In [44]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]


In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [46]:
print(X_train[0:5])

[[2.90287852e+09 6.20000000e+01 6.29400000e-03 1.13200000e-02
  1.54100000e-02 2.60500000e-03 1.07100000e-02 1.14100000e-02
  3.71900000e-05 8.26400000e-02 3.13100000e-02 2.15100000e+00
  4.29200000e-03 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [2.90287852e+09 4.24000000e+02 4.52400000e-03 1.39600000e-02
  1.73600000e-02 6.62200000e-03 1.47400000e-02 1.41100000e-02
  3.62400000e-05 2.24900000e-02 1.90100000e-02 1.96700000e+00
  3.87200000e-03 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [4.94787097e+08 3.00000000e+00 3.83400000e-03 1.14800000e-03
  3.84100000e-03 3.33800000e-04 5.82700000e-04 1.17100000e-03
  3.14700000e-05 1.32000000e-02 1.14300000e-03 9.11300000e+00
  3.62900000e-02 0.00000000e+00 0.00000000e+00 3.23100000e-03]
 [1.71093300e+07 1.11000000e+02 3.30200000e-02 8.36200000e-03
  1.18700000e-02 3.20400000e-03 3.40300000e-03 8.54500000e-03
  9.44100000e-05 1.03600000e-01 1.26500000e-02 3.51900000e+00
  1.06700000e-02 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [1.

In [47]:
print(y_train[0:5])

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]


In [48]:
print(X_test[0:5])

[[1.92299653e+08 7.80000000e+01 1.39200000e-02 2.23400000e-02
  2.90500000e-02 5.58500000e-03 5.69900000e-03 2.23700000e-02
  2.94700000e-04 9.87500000e-02 2.21300000e-03 5.00600000e+00
  1.95500000e-02 0.00000000e+00 0.00000000e+00 1.26800000e-02]
 [2.90287858e+09 2.52000000e+02 9.14000000e-03 1.98100000e-02
  2.50900000e-02 8.63600000e-03 2.15100000e-02 1.99000000e-02
  3.71900000e-05 6.31100000e-02 3.57700000e-02 2.31700000e+00
  4.76400000e-03 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [2.90287858e+09 1.25800000e+03 8.56000000e-03 1.67500000e-02
  2.31600000e-02 5.98100000e-03 1.88600000e-02 1.68800000e-02
  3.71900000e-05 5.01700000e-02 6.34800000e-02 2.30600000e+00
  4.51300000e-03 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [2.90287858e+09 9.93000000e+02 7.96500000e-03 1.58100000e-02
  2.12100000e-02 4.02100000e-03 1.69100000e-02 1.59900000e-02
  3.71900000e-05 4.51700000e-02 3.34500000e-02 2.57100000e+00
  5.98100000e-03 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [2.

In [49]:
print(y_test[0:5])

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]


In [56]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
  ])
model

In [57]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [58]:
model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
80/80 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.9505
Epoch 2/100
80/80 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.9597
Epoch 3/100
80/80 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.9597
Epoch 4/100
80/80 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.9597
Epoch 5/100
80/80 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.9597
Epoch 6/100
80/80 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.9597
Epoch 7/100
80/80 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.9597
Epoch 8/100
80/80 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.9597
Epoch 9/100
80/80 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.9597
Epoch 10/100
80/80 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.9597
Epoch 11/100
80/80 [===================

In [59]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: nan
Test accuracy: 0.9599999785423279


In [60]:
y_pred = model.predict(X_test)
y_pred

32/32 [==============================] - 0s 1ms/step


array([[nan, nan],
       [nan, nan],
       [nan, nan],
       ...,
       [nan, nan],
       [nan, nan],
       [nan, nan]], dtype=float32)

In [ ]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")